import 'package:get/get.dart';

class LocalString extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    "en_US" : {
      "noExercise": "You haven't work-out yet!",
      "loginToYourAccount": "Login to your account",
      "password": "Password",
      "forgotPassword": "Forgot your password?",
      "createAccount": "Create new one ?",
      "signIn": "Sign in",
      "signUp": "Sign up here",
      "searching": "Searching...",
      "targetMuscle": "Target Muscle:",
      "secondaryMuscles": "Secondary muscle:",
      "equipment": "Equipment:",
      "instructions": "Instructions:",
      "startWorkout": "Start workout",
      "start": "Start",
      "done": "Done",
      "serving": "Serving:",
      "duration": "Duration:",
      "ingredients": "Ingredients:",
      "recipe": "Recipe:",
      "date": "Date",
      "thisIsStatistic": "This is your statistic",
      "profile": "Profile",
      "editingProfile": "Editing profile",
      "setting": "Setting",
      "logout": "Log out",
      "home": "Home",
      "nutrition": "Nutition",
      "statistic": "Statistic",
      "theme": "Theme",
      "language": "Languages",
      "selectLanguage": "Select Language",
      "privacyQuestion": "Privacy Question",
      "name": "User name",
      "english": "English",
      "vietnamese": "Vietnamese",
      "personalInformation": "Personal Information",
      "confirmPassword": "Confirm Password",
      "favouriteColor": "What is your favourite color?",
      "exerciseDetail": "Exercise Detail",
      "foodDetail": "Food Detail",
      "congratuation": "Congratuation",

    },
    "vi_VI" : {
      "noExercise": "Bạn chưa tập luyện!",
      "loginToYourAccount": "Đăng nhập",
      "password": "Mật khẩu",
      "forgotPassword": "Quên mật khẩu?",
      "createAccount": "Tạo tài khoản mới ?",
      "signIn": "Đăng nhập",
      "signUp": "Đăng kí ở đây",
      "searching": "Tìm kiếm...",
      "targetMuscle": "Cơ tác động chính:",
      "secondaryMuscles": "Các nhóm cơ phụ:",
      "equipment": "Phụ kiện hỗ trợ:",
      "instructions": "Chỉ dẫn:",
      "startWorkout": "Bắt đầu",
      "start": "Bắt đầu",
      "done": "Hoàn thành",
      "serving": "Số người dùng:",
      "duration": "Thời gian nấu:",
      "ingredients": "Nguyên liệu:",
      "recipe": "Công thức:",
      "date": "Ngày",
      "thisIsStatistic": "Đây là thống kê của bạn",
      "profile": "Thông tin cá nhân",
      "editingProfile": "Sửa thông tin",
      "setting": "Cài đặt",
      "logout": "Đăng xuất",
      "home": "Màn chính",
      "nutrition": "Dinh dưỡng",
      "statistic": "Thống kê",
      "theme": "Chế độ màn hình",
      "language": "Ngôn ngữ",
      "selectLanguage": "Chọn ngôn ngữ",
      "privacyQuestion": "Câu hỏi bảo mật",
      "name": "Tên người dùng",
      "english": "Tiếng Anh",
      "vietnamese": "Tiếng Việt",
      "personalInformation": "Thông tin cá nhân",
      "confirmPassword": "Màu sắc yêu thích của bạn là gì?",
      "exerciseDetail": "Chi tiết bài tập",
      "foodDetail": "Chi tiết món ăn",
      "congratuation": "Chúc mừng",
    }
  };
}